# Automated dependency testing workflow
# Tests all dependency updates thoroughly before merging

name: Dependency Testing

on:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/dependency-test.yml'
  workflow_dispatch:

jobs:
  dependency-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Clear npm cache
        run: npm cache clean --force
      
      - name: Remove existing node_modules
        run: rm -rf node_modules
      
      - name: Fresh dependency install
        run: npm ci
      
      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: false
      
      - name: TypeScript type checking
        run: npm run type-check
        continue-on-error: false
      
      - name: Run ESLint
        run: npm run lint
        continue-on-error: false
      
      - name: Clear Next.js cache
        run: rm -rf .next
      
      - name: Test build process
        run: npm run build
        continue-on-error: false
      
      - name: Check for problematic dependency patterns
        run: |
          # Check for beta/alpha versions that might be problematic
          echo "Checking for beta/alpha dependencies..."
          npm list --depth=0 | grep -E "(beta|alpha|rc|pre)" && exit 1 || echo "No beta/pre-release dependencies found"
          
          # Specifically check for Tailwind CSS v4 beta
          if npm list tailwindcss | grep -E "4\.(0|1|2).*beta"; then
            echo "ERROR: Tailwind CSS v4 beta detected! This is known to cause issues."
            exit 1
          fi